
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    image: evento-frontend
    ports:
      - "3000:3000"
    depends_on:
      - userService
      - companyService

  userService:
    build:
      context: ./backend/userService
      dockerfile: DockerFile
    image: evento-userservice
    ports:
      - "4000:4000"
    environment:
      - mongo_URI=mongodb+srv://ahamedrafirafi03:rafirafi03@cluster0.dzlva.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  companyService:
    build:
      context: ./backend/companyService
      dockerfile: DockerFile
    image: evento-companyservice
    ports:
      - "4001:4001"
    environment:
      - MONGO_URI=mongodb+srv://rafi03:rafirafi03@cluster0.d8exz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
