apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: rafi03/company-service:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
spec:
  type: ClusterIP
  selector:
    app: company
  ports:
    - port: 3002
      targetPort: 3002