apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
    spec:
      containers:
      - name: company-service
        image: rafi03/company-service:latest
        ports:
        - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: company-service
spec:
  selector:
    app: company-service
  ports:
  - port: 80
    targetPort: 4001
  type: ClusterIP