apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: rafi03/user-service:latest
        ports:
        - containerPort: 4000
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - name: http-port       # Added name for HTTP port
    port: 4000            # HTTP port
    targetPort: 4000      # HTTP port on the container
  - name: grpc-port       # Added name for gRPC port
    port: 50051           # gRPC port
    targetPort: 50051     # gRPC port on the container
  type: ClusterIP